project:
  type: website
  output-dir: docs

website:
  title: "Emma Pingel"
  navbar:
    left:
      - href: home.qmd
        text: Home
      - href: resume.qmd
        text: Resume 
      - href: projects.qmd
        text: Project Samples

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

